### ISSUE TITLE
Incubator for non-profit projects

### ISSUE THREAD

**Issue by deuzu** [24chevres/24chevres.com#28]
What do you guys think about 24chevres.com being an incubator for non-profit projects?
We could focus on charity projects then expand to non-charity (or the other way around).
Like [what Toyota did for the The Food Bank for New York City](http://www.nytimes.com/2013/07/27/nyregion/in-lieu-of-money-toyota-donates-efficiency-to-new-york-charity.html): donating efficiency, but distrubuted.

It could join @izeau 's speadshirt idea starting with a single page:
> Buy our awesome T-shirt to help us build a 100% transparency and ethic non-profit plateform.

On top of that, block chain and a new crypto currency to handle transparent transaction exchanges.

@24chevres/chevres

**Comment by nsantosdaveiga** [comment]
I'm in

**Comment by izeau** [comment]
What about P2P distributed encrypted blockchain-based crypto-traffic? Can we do something webscale, frictionless and disruptive?

**Comment by tiagojdf** [comment]
Have you guys read "A world of 3 zeros"? The gist of it is that by using social business instead of charities you can help a lot more people. Instead of trying to do charity, you set up a business activity that is self-funding and you use the revenue to expand the business to reach a broader audience. What distinguishes it from a classical business model is that your goal is not profitability, but some higher goal. For example, instead of setting up uber with the goal of making $$$, you set up a transportation service whose goal is to allow low income families without access to a car to have some form of transportation.

If someone wants to read it in english, I can lend them my copy.

**Comment by deuzu** [comment]
@izeau Can you lighten us about the functionnal implementation on such a system please :D 

@Tiagojdferreira I like the idea.
We could either build a social business with one goal or help social businesses to grow. I like the 2nd option more.

**Comment by tiagojdf** [comment]
@deuzu there are some institutions that already do that here in Paris. We should try to contact them and see how we can implement a similar structure with focus on web projects. The founder of the movement, and writer of the book is called Muhammad Yunus, so most of those institutions have Yunus in their name. I will try to give some more details during the week.

**Comment by deuzu** [comment]
What we have so far: 
  - a p2p crypto currency project
  - something around social business 
  - a project incubator (charity, non profit, social business) 

I want 24chevres to be a playground where people play with new technologies. That's why I like the idea of the incubator / kick-starter. We could build (or help build) small to medium projects using promising technologies. Where projects could be somewhere between fun and serious (why not both?).

@24chevres/chevres should we move forward with the idea of a playground platform at the cutting edge of technology? By doing that we could fit *almost* everyone ideas (like those listed above) in the project.

**Comment by nsantosdaveiga** [comment]
je suis chaud (pourquoi vous parlez anglais ?)

**Comment by hanfi** [comment]
a funny idea and i think nobody have implemented it yet, honestly this looks fun and challenging to do. 
it's also based on technologies that none of us have mastered, i think also that it have good business value : 
https://www.reddit.com/r/SnapCatFilters/
i think about a mobile app that can also work with goats, dogs, rabbits but wont work with humains.

**Comment by hanfi** [comment]
it can be really fun to put luxury clothes and accessories on animals.

**Comment by deuzu** [comment]
@hanfi It seems that everyone want to be involved in multiple ideas.
I'll try to start something the allow us to push ideas and work together on it.
Keep tuned @24chevres/chevres

@nsantosdaveiga Parce que 24chevres est un projet open source et international 🌐 💪 🤘 :trollface: 🐐

**Comment by deuzu** [comment]
# 24chevres a community for greater goods.


## Objectives

  - X actives members
  - X succeed projects
  - having X existing projects joining 24chevres


## 1st milestone

### Homepage

Explain what we want to do and offer a newsletter subscription. (and sell shirts?)

*scroll down*

Check out our projects for greater good!
A link to a new page + 3 to 5 24chevres projects

*scroll down*

I want to be part of the community!
3 options:
  - send a application
  - have a PR merged on a 24chevres project
  - propose a project


### Application page

todo


### Projects listing page

todo


### First project

It have to fit the idea of 24chevres perfectly.

  - @izeau's crypto currency idea?
  - @souhail's snap filters for pets?
  - @tiago's social business?


## To be defined

  - every one can propose a project on the website?
  - Projects hosted on Github under 24chevres organization or owned by people?
  - Who can commit to repositories? Github-democrate only?
  - Which technologies use?

@24chevres/chevres what do you think?

**Comment by deuzu** [comment]
It has already started!
